version: '3.4'

services:
  documentation:
    image: hugo-image
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:pa.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr

networks:
  default:
    external:
      name: traefik-net
